In [1]:
import ast
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('tdk_word_data_all.csv')
df.head(3)

,madde_id,kac,kelime_no,cesit,anlam_gor,on_taki,madde,cesit_say,anlam_say,taki,...,ozel_mi,lisan_kodu,lisan,telaffuz,birlesikler,font,madde_duz,gosterim_tarihi,anlamlarListe,atasozu
0,6142,0,5,0,0,NaN,acınılma,0,1,NaN,...,0,0,NaN,NaN,NaN,NaN,acinilma,NaN,"[{'anlam_id': '1', 'madde_id': '6142', 'anlam_...",NaN
1,6143,0,6,0,0,NaN,acube,0,2,NaN,...,0,11,Arapça uʿcūbe,acu:be,NaN,NaN,acube,NaN,"[{'anlam_id': '2', 'madde_id': '6143', 'anlam_...",NaN
2,6144,0,7,0,0,NaN,açık fikirlilik,0,1,ği,...,0,0,NaN,NaN,NaN,NaN,acik fikirlilik,NaN,"[{'anlam_id': '4', 'madde_id': '6144', 'anlam_...",NaN

In [4]:
df = df[['madde', 'anlamlarListe']]
df.head(3)

             madde                                      anlamlarListe
0         acınılma  [{'anlam_id': '1', 'madde_id': '6142', 'anlam_...
1            acube  [{'anlam_id': '2', 'madde_id': '6143', 'anlam_...
2  açık fikirlilik  [{'anlam_id': '4', 'madde_id': '6144', 'anlam_...

In [5]:
df['anlamlarListe'].fillna('[]', inplace=True)
df['anlamlarListe'] = df['anlamlarListe'].apply(ast.literal_eval)
anlam_list = df['anlamlarListe'].apply(lambda x: x[0]['anlam'] if x else 'No Data')
df['anlam'] = anlam_list
df.drop('anlamlarListe', axis=1, inplace=True)

df.head(3)

             madde                     anlam
0         acınılma             Acınılmak işi
1            acube               Tuhaf kimse
2  açık fikirlilik  Açık fikirli olma durumu

In [6]:
df.head(10)

             madde                                              anlam
0         acınılma                                      Acınılmak işi
1            acube                                        Tuhaf kimse
2  açık fikirlilik                           Açık fikirli olma durumu
3        adaklanma                                         Nişanlanma
4      adaletlilik                               Adaletli olma durumu
5          addetme                                              Sayma
6        addolunma                                            Sayılma
7       adli polis  Adliye içerisinde güvenliği sağlayıp cumhuriye...
8       aforozlama                                    Aforozlamak işi
9        afsunlama                                           Büyüleme

In [7]:
df.to_csv('tdk_word_meaning_data.csv', index=False)